version: '3'

tasks:

  build:
    desc: "Builda as imagens Docker."
    cmds:
      - docker-compose build

  bootstrap-quina:
    desc: "Realiza o bootstrap de dados históricos da Quina."
    cmds:
      - task: bootstrap
        vars:
          LOTERIA: "quina"

  bootstrap-lotofacil:
    desc: "Realiza o bootstrap de dados históricos da Lotofácil."
    cmds:
      - task: bootstrap
        vars:
          LOTERIA: "lotofacil"
  
  bootstrap-megasena:
    desc: "Realiza o bootstrap de dados históricos da Mega-Sena."
    cmds:
      - task: bootstrap
        vars:
          LOTERIA: "megasena"

  bootstrap:
    internal: true
    desc: "Realiza o bootstrap de dados históricos de uma loteria a partir de um arquivo .xlsx."
    cmds:
      - docker-compose run --rm app python scripts/bootstrap.py {{.LOTERIA}}

  update-quina:
    desc: "Atualiza os resultados da Quina."
    cmds:
      - task: update
        vars:
          LOTERIA: "quina"
  
  update-lotofacil:
    desc: "Atualiza os resultados da Lotofácil."
    cmds:
      - task: update
        vars:
          LOTERIA: "lotofacil"

  update-megasena:
    desc: "Atualiza os resultados da Mega-Sena."
    cmds:
      - task: update
        vars:
          LOTERIA: "megasena"

  update:
    interactive: true
    desc: "Atualiza os resultados de uma loteria."
    cmds:
      - docker-compose run --rm app python scripts/update.py {{.LOTERIA}}

  test:
    desc: "Roda os testes com pytest"
    cmds:
      - docker-compose run --rm app pytest